###### Imports and Settings

In [1]:
import pandas as pd
import numpy as np
import requests

# Request from Special Projects Manager  

*For the 13 County Region*

+ total population  
+ minority (non-white, non hispanic)  
+ 60+ population  
+ 60+ minority population  

13 Counties: Stewart, Montgomery, Houston, Humphreys, Dickson, Cheatham, Robertson, Sumner, Davidson, Wilson, Trousdale, Williamson, Rutherford

In [2]:
api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'

In [3]:
GNRC = ['161', #Stewart
       '125', #Montgomery
       '083', #Houston
       '085', #Humphreys
       '043', #Dickson
       '021', #Cheatham
       '147', #Robertson
       '165', #Sumner
       '037', #Davidson
       '189', #Wilson
       '169', #Trousdale
       '187', #Williamson
       '149'] #Rutherford

## Population 55 and 65+, minorities.

In [60]:
#sexbyagewhitealonenothisporlatino
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= ["NAME", "GEO_ID",'B01001_017E','B01001_018E','B01001_019E','B01001_020E','B01001_021E','B01001_022E','B01001_023E','B01001_024E','B01001_025E','B01001_041E','B01001_042E','B01001_043E','B01001_044E','B01001_045E','B01001_046E','B01001_047E','B01001_048E','B01001_049E','B01001H_013E','B01001H_014E','B01001H_015E','B01001H_016E','B01001H_028E','B01001H_029E','B01001H_030E','B01001H_031E']
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = ['County', 'GEOID','m55_59','m60_61','m62_64','m65_66','m67_69','m70_74','m75_79','m80_84','m85+','fm55_59','fm60_61','fm62_64','fm65_66','fm67_69','fm70_74','fm75_79','fm80_84','fm85+','Wm55_64','Wm65_74','Wm75_84','Wm85+','Wf55_64','Wf65_74','Wf75_84','Wf85+','StateFIPS','CountyFIPS']
    data=pd.DataFrame(columns=col_names, data=data.json()[1:])
    data['Region'] = 'GNRC'
    data_appended.append(data)
    
data_appended = pd.concat(data_appended)
data = data_appended
print('Your API call is complete')

Your API call is complete

In [61]:
data.head()

,County,GEOID,m55_59,m60_61,m62_64,m65_66,m67_69,m70_74,m75_79,m80_84,...,Wm65_74,Wm75_84,Wm85+,Wf55_64,Wf65_74,Wf75_84,Wf85+,StateFIPS,CountyFIPS,Region
0,"Stewart County, Tennessee",0500000US47161,459,283,227,209,272,291,191,113,...,749,304,129,959,790,488,113,47,161,GNRC
0,"Montgomery County, Tennessee",0500000US47125,4623,2116,2378,1684,1912,1930,1315,866,...,4318,1794,629,7154,4750,2434,944,47,125,GNRC
0,"Houston County, Tennessee",0500000US47083,311,175,106,73,169,237,164,54,...,448,210,67,554,478,323,58,47,083,GNRC
0,"Humphreys County, Tennessee",0500000US47085,685,271,333,198,284,502,398,177,...,984,575,60,1321,1075,680,154,47,085,GNRC
0,"Dickson County, Tennessee",0500000US47043,1571,801,1120,615,768,1056,667,460,...,2278,1096,249,3563,2579,1282,637,47,043,GNRC

In [62]:
cols = ['m55_59','m60_61','m62_64','m65_66','m67_69','m70_74','m75_79','m80_84','m85+','fm55_59','fm60_61','fm62_64',
        'fm65_66','fm67_69','fm70_74','fm75_79','fm80_84','fm85+','Wm55_64','Wm65_74','Wm75_84','Wm85+','Wf55_64','Wf65_74','Wf75_84','Wf85+']
data[cols] = data[cols].astype(int)

In [63]:
#data.info()

In [64]:
data['total55+'] = data['m55_59']+data['m60_61']+data['m62_64']+data['m65_66']+data['m67_69']+data['m70_74']+data['m75_79']+data['m80_84']+data['m85+']+data['fm55_59']+data['fm60_61']+data['fm62_64']+data['fm65_66']+data['fm67_69']+data['fm70_74']+data['fm75_79']+data['fm80_84']+data['fm85+']
data['total65+'] = data['m65_66']+data['m67_69']+data['m70_74']+data['m75_79']+data['m80_84']+data['m85+']+data['fm65_66']+data['fm67_69']+data['fm70_74']+data['fm75_79']+data['fm80_84']+data['fm85+']
data['total55+notminority'] = data['Wm55_64']+data['Wm65_74']+data['Wm75_84']+data['Wm85+']+data['Wf55_64']+data['Wf65_74']+data['Wf75_84']+data['Wf85+']
data['total65+notminority'] = data['Wm65_74']+data['Wm75_84']+data['Wm85+']+data['Wf65_74']+data['Wf75_84']+data['Wf85+']

In [65]:
df = data[['County','GEOID','total55+','total65+','total55+notminority','total65+notminority']].reset_index(drop = True)

In [66]:
df['minority55+'] = df['total55+']-df['total55+notminority']
df['minority65+'] = df['total65+']-df['total65+notminority']

In [67]:
df['%minority55+'] = round((df['minority55+']/df['total55+'])*100, 2)
df['%minority65+'] = round((df['minority65+']/df['total65+'])*100, 2)

In [68]:
df.head()

,County,GEOID,total55+,total65+,total55+notminority,total65+notminority,minority55+,minority65+,%minority55+,%minority65+
0,"Stewart County, Tennessee",0500000US47161,4666,2678,4462,2573,204,105,4.37,3.92
1,"Montgomery County, Tennessee",0500000US47125,38586,19065,28381,14869,10205,4196,26.45,22.01
2,"Houston County, Tennessee",0500000US47083,2874,1692,2679,1584,195,108,6.78,6.38
3,"Humphreys County, Tennessee",0500000US47085,6280,3593,6115,3528,165,65,2.63,1.81
4,"Dickson County, Tennessee",0500000US47043,15914,8513,14896,8121,1018,392,6.40,4.60

### Now get counts.

In [69]:
counts = data[['total55+','total65+','total55+notminority','total65+notminority','Region']].groupby('Region').sum()

In [70]:
counts

        total55+  total65+  total55+notminority  total65+notminority
Region
GNRC      491717    254676               396914               213092

In [71]:
minority55 = counts['total55+'] - counts['total55+notminority']
percminority55 = (minority55/counts['total55+'])*100
print(minority55, percminority55)

Region
GNRC    94803
dtype: int32 Region
GNRC    19.279992
dtype: float64

In [72]:
minority65 = counts['total65+'] - counts['total65+notminority']
percminority65 = (minority65/counts['total65+'])*100
print(minority65, percminority65)

Region
GNRC    41584
dtype: int32 Region
GNRC    16.328197
dtype: float64

**There are 476,746 people total over 55, and 258,687 total people over 65. <-- 2019**  
**There are 491,717 people total over 55, and 254,676 total people over 65. <-- 2020**

**There are 88,918 minorities over age 55 (18.65% of age group), and 38,818 minorities over age 65 (15.87% of age group).<--2019**   
**There are 94,803 minorities over age 55 (19.28% of age group), and 41,584 minorities over age 65 (16.33% of age group).<--2020**

The minority status by age is limited to either 55+ or 65+, unfortunately the only other option is the subject tables which don't collect data for counties below a certain population which in our case include Stewart, Houston, Humphreys, and Trousdale counties.

## Total and total minority population.

In [73]:
#acs tables
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= ["NAME", "GEO_ID", 'B01003_001E','B03002_003E'] #this is the total population that goes with this data series, it is the same as total pop.
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = ['County', 'GEOID','total','nothisp_whitealone','StateFIPS', 'CountyFIPS']
    data=pd.DataFrame(columns=col_names, data=data.json()[1:])
    data['Region'] = 'GNRC'
    data_appended.append(data)
    
data_appended = pd.concat(data_appended)
total = data_appended.reset_index(drop = True)
print('Your API call is complete')

Your API call is complete

In [74]:
total.head(13)

,County,GEOID,total,nothisp_whitealone,StateFIPS,CountyFIPS,Region
0,"Stewart County, Tennessee",0500000US47161,13553,12397,47,161,GNRC
1,"Montgomery County, Tennessee",0500000US47125,204992,128270,47,125,GNRC
2,"Houston County, Tennessee",0500000US47083,8201,7521,47,083,GNRC
3,"Humphreys County, Tennessee",0500000US47085,18528,16915,47,085,GNRC
4,"Dickson County, Tennessee",0500000US47043,53289,47624,47,043,GNRC
5,"Cheatham County, Tennessee",0500000US47021,40539,37206,47,021,GNRC
6,"Robertson County, Tennessee",0500000US47147,70982,58524,47,147,GNRC
7,"Sumner County, Tennessee",0500000US47165,187680,155517,47,165,GNRC
8,"Davidson County, Tennessee",0500000US47037,690540,386782,47,037,GNRC
9,"Wilson County, Tennessee",0500000US47189,140604,117685,47,189,GNRC
10,"Trousdale County, Tennessee",0500000US47169,10910,9007,47,169,GNRC
11,"Williamson County, Tennessee",0500000US47187,232380,194587,47,187,GNRC
12,"Rutherford County, Tennessee",0500000US47149,324139,225604,47,149,GNRC

In [75]:
cols = ['total', 'nothisp_whitealone']
total[cols] = total[cols].astype(int)

In [76]:
total['minority'] = total['total'] - total['nothisp_whitealone']
total['%minority'] = round((total['minority']/total['total'])*100, 2)

### Now get counts.

In [77]:
counts = total[['total','nothisp_whitealone','Region']].groupby('Region').sum()
counts

          total  nothisp_whitealone
Region
GNRC    1996337             1397639

In [78]:
minority = counts['total'] - counts['nothisp_whitealone']
minority

Region
GNRC    598698
dtype: int32

In [79]:
percminority = (minority/counts['total'])*100
percminority

Region
GNRC    29.989826
dtype: float64

**The total population is 1,962,373, and of that the total minority population is 576,321 (29.37% of the total population). <-- 2019**

**The total population is 1,996,337, and of that the total minority population is 598,698 (29.99% of the total population). <-- 2020**

## Combine appropriate data to create a map so we can visualize the total minority dispersement between counties compared to the older minorities.

In [80]:
df = df.drop(columns = ['County'])

In [81]:
joined = total.merge(df, on='GEOID', how='inner')

In [82]:
joined.head()

,County,GEOID,total,nothisp_whitealone,StateFIPS,CountyFIPS,Region,minority,%minority,total55+,total65+,total55+notminority,total65+notminority,minority55+,minority65+,%minority55+,%minority65+
0,"Stewart County, Tennessee",0500000US47161,13553,12397,47,161,GNRC,1156,8.53,4666,2678,4462,2573,204,105,4.37,3.92
1,"Montgomery County, Tennessee",0500000US47125,204992,128270,47,125,GNRC,76722,37.43,38586,19065,28381,14869,10205,4196,26.45,22.01
2,"Houston County, Tennessee",0500000US47083,8201,7521,47,083,GNRC,680,8.29,2874,1692,2679,1584,195,108,6.78,6.38
3,"Humphreys County, Tennessee",0500000US47085,18528,16915,47,085,GNRC,1613,8.71,6280,3593,6115,3528,165,65,2.63,1.81
4,"Dickson County, Tennessee",0500000US47043,53289,47624,47,043,GNRC,5665,10.63,15914,8513,14896,8121,1018,392,6.40,4.60

### Write out file, bring in geo and map in next notebook.

In [83]:
joined.to_csv('../data/joined.csv')

## Subject tables have minority status by over 60, but only for select counties. Did not pursue.

In [143]:
# #subject tables
# data_appended = []
# for i in GNRC:
#     url_str= 'https://api.census.gov/data/2019/acs/acs5/subject?key='+api_key
#     predicates= {}
#     get_vars= ["NAME", 'S0101_C01_028E','S0102_C02_001E','S0102_C02_014E','S0102_C01_006E','S0501_C01_023E']
#     predicates["get"]= ",". join(get_vars)
#     predicates["for"]= "county:{}".format(i)
#     predicates["in"]= "state:47"
#     data= requests.get(url_str, params= predicates)
#     col_names = ['County', '60+','60+','whitealone_nothisp60+','onerace_white','whitenothisp_totalpop','StateFIPS', 'CountyFIPS']
#     data=pd.DataFrame(columns=col_names, data=data.json()[1:])
#     data['Estimate'] = '2016_2020'
#     data_appended.append(data)
    
# data_appended = pd.concat(data_appended)
# data = data_appended
# print('Your API call is complete')

In [144]:
#data.head(13)